name: Setup Next.js

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  install_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm install
