name: Setup Next.js
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-dependecies:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      # - name: Build
      #   run: npm run build

      - name: Run my action
        uses: ./
