name: Setup Next.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-node:
    name: Setup Nodejs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
  install-dependecies:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test

